# All Target
all:
	clang++ `pkgconf --cflags PcapPlusPlus`-c -o main.o main.cpp
	clang++ -o PcapPlusPlusTestApp main.o `pkgconf --libs PcapPlusPlus`

# Clean Target
clean:
	rm main.o
	rm PcapPlusPlusTestApp
