# All Target
all:
	g++ `pkg-config --cflags PcapPlusPlus` -c -o main.o main.cpp
	g++ -o PcapPlusPlusTestApp main.o `pkg-config --libs PcapPlusPlus`

# Clean Target
clean:
	rm main.o
	rm PcapPlusPlusTestApp
