include /usr/local/etc/PcapPlusPlus.mk

# All Target
all:
	clang++ $(PCAPPP_BUILD_FLAGS) $(PCAPPP_INCLUDES) -c -o main.o main.cpp
	clang++ $(PCAPPP_LIBS_DIR) -static-libstdc++ -o PcapPlusPlusTestApp main.o $(PCAPPP_LIBS)

# Clean Target
clean:
	rm main.o
	rm PcapPlusPlusTestApp
